# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LUl2MN5mZhHnZKuLMYdCPs8I6pI7cEws
"""

import time
import numpy as np
import torch

from stress_utils import compute_stress
from stability import AdvancedStabilityFilter

class LiveEEGEngine:
    def __init__(self, model, device):
        self.model = model.to(device)
        self.device = device
        self.model.eval()

        # Stability filter (window size = 5)
        self.stability = AdvancedStabilityFilter(5)

    def predict(self, eeg_epoch):
        start_time = time.time()

        X = torch.tensor(
            eeg_epoch, dtype=torch.float32
        ).unsqueeze(0).to(self.device)

        with torch.no_grad():
            outputs = self.model(X)

        latency = round((time.time() - start_time) * 1000, 2)

        # ---------------- Emotion ----------------
        emotion_out = outputs["emotion"]
        emotion_logits = emotion_out.detach().cpu().numpy()[0]

        emotion_probs = np.exp(emotion_logits) / np.sum(np.exp(emotion_logits))
        raw_emotion = int(np.argmax(emotion_probs))
        emotion_confidence = float(np.max(emotion_probs))

        emotion_pred, emotion_conf = self.stability.update(
            prediction=raw_emotion,
            confidence=emotion_confidence,
            prob_vector=emotion_probs
        )

        # ---------------- Task ----------------
        task_logits = outputs["task"]
        task_logits = task_logits.detach().cpu().numpy()[0]

        task_probs = np.exp(task_logits) / np.sum(np.exp(task_logits))
        task_pred = int(np.argmax(task_probs))
        task_conf = float(np.max(task_probs))

        # ---------------- Vision (FIXED) ----------------
        vision_out = outputs["vision"]
        vision_logits = vision_out.detach().cpu().numpy()[0]

        vision_probs = np.exp(vision_logits) / np.sum(np.exp(vision_logits))
        vision_pred = int(np.argmax(vision_probs))
        vision_conf = float(np.max(vision_probs))

        # ---------------- Stress ----------------
        stress_signal = compute_stress(eeg_epoch)

        return {
            "emotion": {
                "prediction": emotion_pred,
                "confidence": emotion_conf
            },
            "task": {
                "prediction": task_pred,
                "confidence": task_conf
            },
            "vision": {
                "prediction": vision_pred,
                "confidence": vision_conf
            },
            "stress_signal": stress_signal,
            "latency_ms": latency
        }