# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12o_4z7V4MCYEH0_OTQftyNN2L_HadpVF

model.py
---------
Transformer-based Multi-Task EEG Model

Tasks:
1. Emotion recognition
2. Mental task classification
3. Visual stimulus classification

Architecture:
EEG → Linear Embedding → Transformer Encoder → Shared Representation
→ Task-specific output heads
"""

import torch
import torch.nn as nn
import math

"""# Transformer-based Multi-Task EEG Model WITH EXPLAINABILITY

"""

# ======================================================
# CUSTOM TRANSFORMER ENCODER LAYER (WITH ATTENTION)
# ======================================================
class TransformerEncoderWithAttention(nn.Module):
    def __init__(self, embed_dim, num_heads, dropout=0.1):
        super().__init__()

        self.self_attn = nn.MultiheadAttention(
            embed_dim=embed_dim,
            num_heads=num_heads,
            batch_first=True
        )

        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)

        self.ff = nn.Sequential(
            nn.Linear(embed_dim, embed_dim * 4),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(embed_dim * 4, embed_dim)
        )

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # Self-attention
        attn_out, attn_weights = self.self_attn(
            x, x, x, need_weights=True
        )
        x = self.norm1(x + self.dropout(attn_out))

        # Feed-forward
        ff_out = self.ff(x)
        x = self.norm2(x + self.dropout(ff_out))

        return x, attn_weights

import torch
import torch.nn as nn
import math

# ---------------- Positional Encoding ----------------
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=1024):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        pos = torch.arange(0, max_len).unsqueeze(1)
        div = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div)
        self.register_buffer("pe", pe.unsqueeze(0))

    def forward(self, x):
        return x + self.pe[:, :x.size(1)]

class EEGEncoder(nn.Module):
    def __init__(self, ch, d=128, heads=8, layers=4):
        super().__init__()
        self.proj = nn.Linear(ch, d)
        self.pos = PositionalEncoding(d)

        self.attn_layers = nn.ModuleList()
        self.ffn_layers = nn.ModuleList()
        self.norm1 = nn.ModuleList()
        self.norm2 = nn.ModuleList()

        for _ in range(layers):
            self.attn_layers.append(
                nn.MultiheadAttention(d, heads, batch_first=True)
            )
            self.ffn_layers.append(
                nn.Sequential(
                    nn.Linear(d, d * 4),
                    nn.ReLU(),
                    nn.Linear(d * 4, d)
                )
            )
            self.norm1.append(nn.LayerNorm(d))
            self.norm2.append(nn.LayerNorm(d))

    def forward(self, x, return_attention=False):
        x = x.permute(0, 2, 1)
        x = self.pos(self.proj(x))

        attns = []

        for attn, ffn, n1, n2 in zip(
            self.attn_layers, self.ffn_layers, self.norm1, self.norm2
        ):
            attn_out, w = attn(x, x, x)
            x = n1(x + attn_out)

            ffn_out = ffn(x)
            x = n2(x + ffn_out)

            attns.append(w)

        feat = x.mean(dim=1)
        return (feat, attns) if return_attention else feat

# ---------------- Multi-task Model ----------------
class MultiTaskEEGTransformer(nn.Module):
    def __init__(self, n_channels, num_task_classes):
        super().__init__()

        self.enc = EEGEncoder(n_channels)

        self.emotion = nn.Linear(128, 2)
        self.task    = nn.Linear(128, num_task_classes)
        self.vision  = nn.Linear(128, 2)
        self.stress  = nn.Linear(128, 3)

    def forward(self, x, return_attention=False):
        if return_attention:
            features, attn = self.enc(x, return_attention=True)
        else:
            features = self.enc(x)
            attn = None

        return {
            "emotion": self.emotion(features),
            "task":    self.task(features),
            "vision":  self.vision(features),
            "stress":  self.stress(features),
            "attentions": attn
        }