# -*- coding: utf-8 -*-
"""stability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181W5BpO8xZDaUdQOhMBC9ew14UJnE6Se
"""

import numpy as np
from collections import deque
from scipy.stats import entropy

def prediction_entropy(probabilities):
    """
    probabilities: 1D numpy array (softmax output)
    returns: entropy (uncertainty)
    """
    probabilities = np.clip(probabilities, 1e-8, 1.0)
    return entropy(probabilities)

class AdvancedStabilityFilter:
    """
    Advanced temporal stability filter for real-time EEG predictions.

    Features:
    - Confidence-weighted voting
    - Entropy-aware smoothing
    - Adaptive window size
    """

    def __init__(
        self,
        base_window=5,
        max_window=15,
        entropy_threshold=0.8
    ):
        self.base_window = base_window
        self.max_window = max_window
        self.entropy_threshold = entropy_threshold

        self.pred_buffer = deque(maxlen=max_window)
        self.conf_buffer = deque(maxlen=max_window)
        self.ent_buffer  = deque(maxlen=max_window)

    def update(self, prediction, confidence, prob_vector=None):
        """
        prediction  : int
        confidence  : float (max softmax probability)
        prob_vector : optional softmax vector for entropy
        """

        # Compute entropy if probability vector provided
        ent = prediction_entropy(prob_vector) if prob_vector is not None else 0.0

        self.pred_buffer.append(prediction)
        self.conf_buffer.append(confidence)
        self.ent_buffer.append(ent)

        # -------------------------------
        # Adaptive window size
        # -------------------------------
        avg_entropy = np.mean(self.ent_buffer)
        if avg_entropy > self.entropy_threshold:
            window = min(len(self.pred_buffer), self.max_window)
        else:
            window = min(len(self.pred_buffer), self.base_window)

        preds = list(self.pred_buffer)[-window:]
        confs = list(self.conf_buffer)[-window:]

        # -------------------------------
        # Confidence-weighted voting
        # -------------------------------
        weighted_votes = {}
        for p, c in zip(preds, confs):
            weighted_votes[p] = weighted_votes.get(p, 0) + c

        final_pred = max(weighted_votes, key=weighted_votes.get)

        # Stability confidence
        stability_conf = weighted_votes[final_pred] / sum(weighted_votes.values())

        return final_pred, round(stability_conf, 3)

def smooth_prediction_sequence(preds, confs, window=5):
    """
    Offline temporal smoothing for evaluation plots.
    """
    smoothed = []

    for i in range(len(preds)):
        start = max(0, i - window + 1)
        p_slice = preds[start:i+1]
        c_slice = confs[start:i+1]

        votes = {}
        for p, c in zip(p_slice, c_slice):
            votes[p] = votes.get(p, 0) + c

        smoothed.append(max(votes, key=votes.get))

    return smoothed

# Simulated real-time predictions
np.random.seed(42)

filter_rt = AdvancedStabilityFilter()

for t in range(12):
    fake_probs = np.random.dirichlet([1, 1, 1])
    pred = np.argmax(fake_probs)
    conf = fake_probs[pred]

    stable_pred, stable_conf = filter_rt.update(
        pred,
        conf,
        prob_vector=fake_probs
    )

    print(
        f"Step {t:02d} | Raw: {pred} | "
        f"Stable: {stable_pred} | "
        f"Conf: {stable_conf}"
    )