# -*- coding: utf-8 -*-
"""stress_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a3z0fFGHI8W6LrDeUQYmOL4vGKzAxYvb
"""

import numpy as np
from scipy.signal import welch

def bandpower(signal, fs, band):
    """
    Compute band power using Welch PSD.

    signal : 1D array (time)
    fs     : sampling frequency
    band   : tuple (low_freq, high_freq)
    """
    freqs, psd = welch(signal, fs)
    idx = np.logical_and(freqs >= band[0], freqs <= band[1])
    return np.trapz(psd[idx], freqs[idx])

def compute_stress_label(eeg_epoch, fs=256):
    """
    eeg_epoch : shape (channels, time)
    returns   : stress label (0, 1, 2)
    """
    alpha = bandpower(eeg_epoch.mean(axis=0), fs, (8, 13))
    beta  = bandpower(eeg_epoch.mean(axis=0), fs, (13, 30))

    stress_index = beta / (alpha + 1e-6)

    if stress_index < 0.8:
        return 0  # Low
    elif stress_index < 1.2:
        return 1  # Medium
    else:
        return 2  # High

def compute_stress_index(eeg_epoch, fs=256):
    """
    eeg_epoch : shape (channels, time)
    returns   : (mean_stress_index, std_stress_index)
    """
    stress_values = []

    for ch in range(eeg_epoch.shape[0]):
        alpha = bandpower(eeg_epoch[ch], fs, (8, 13))
        beta  = bandpower(eeg_epoch[ch], fs, (13, 30))
        stress_values.append(beta / (alpha + 1e-6))

    return np.mean(stress_values), np.std(stress_values)

def stress_label_from_index(index):
    """
    Map stress index to discrete stress class
    """
    if index < 0.8:
        return 0  # Low
    elif index < 1.2:
        return 1  # Medium
    else:
        return 2  # High

def compute_stress(eeg_epoch, fs=256):
    """
    Full stress estimation with confidence.

    eeg_epoch : shape (channels, time)
    returns   : dict with index, variability, label, confidence
    """
    mean_idx, std_idx = compute_stress_index(eeg_epoch, fs)
    label = stress_label_from_index(mean_idx)

    # Confidence inversely proportional to variability
    confidence = 1 / (1 + std_idx)

    return {
        "stress_index": round(mean_idx, 3),
        "stress_variability": round(std_idx, 3),
        "stress_label": label,
        "confidence": round(confidence, 3)
    }

# Dummy EEG epoch for testing
if __name__ == "__main__":
    dummy_eeg = np.random.randn(32, 256)
    print(compute_stress(dummy_eeg, fs=256))